- name: Install and configure NGINX using variables
  hosts: web
  become: true
  vars:
    nginx_pkg: nginx
    nginx_service: nginx

  tasks:
    - name: Install NGINX
      apt:
        name: "{{ nginx_pkg }}"
        state: present
        update_cache: yes

    - name: Start and enable NGINX service
      service:
        name: "{{ nginx_service }}"
        state: started
        enabled: yes
